#!/usr/bin/env sh

case $1 in
	toggle) amixer -D pulse sset Master toggle ;;
	inc) amixer -D pulse sset Master 5%+ >/dev/null 2>/dev/null ;;
	dec) amixer -D pulse sset Master 5%- >/dev/null 2>/dev/null ;;
esac

