#!/usr/bin/env sh

case $1 in
	toggle) notify-send "Audio toggled $(amixer -D pulse sset Master toggle | awk '{print $6}' | tail -n 1)"; ;;
	inc) notify-send "Audio increased to: $(amixer -D pulse sset Master 5%+ | awk '{print $5'} | tail -n 1)";;
	dec) notify-send "Audio decreased to: $(amixer -D pulse sset Master 5%- | awk '{print $5'} | tail -n 1)";;
esac

